In [ ]:
import numpy as np


In [ ]:
A1=np.array([1,2,3,4])
print(A1)

[1 2 3 4]


In [ ]:
type(A1)

numpy.ndarray

In [ ]:
A1.shape

(4,)

In [ ]:
A1.size

4

In [ ]:
A2=np.array([[1,2,3,4],[5,6,7,8]])
print(A2)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
A2.size

8

In [ ]:
A2.ndim

2

In [ ]:
A2.shape

(2, 4)

In [ ]:
A3=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
print(A3)


[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


In [ ]:
A3.ndim

3

In [ ]:
A3.shape

(2, 2, 4)

In [ ]:
A3.size

16

In [ ]:
A4=np.array([[[[1,2,3],[5,6,7]],[[9,10,11],[13,14,15]]],[[[1,2,3],[5,6,7]],[[9,10,11],[13,14,15]]]])
print(A4)

[[[[ 1  2  3]
   [ 5  6  7]]

  [[ 9 10 11]
   [13 14 15]]]


 [[[ 1  2  3]
   [ 5  6  7]]

  [[ 9 10 11]
   [13 14 15]]]]


In [ ]:
A4.ndim

4

In [ ]:
A4.size

24

In [ ]:
A4.shape

(2, 2, 2, 3)

In [ ]:
import numpy as np
Z1=np.zeros(4)
print(Z1)

[0. 0. 0. 0.]


In [ ]:
np.zeros(4,dtype=int)

array([0, 0, 0, 0])

In [ ]:
Z1=np.zeros((2,3,4),dtype=int)
print(Z1)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [ ]:
Z1.size

24

In [ ]:
Z1.shape

(2, 3, 4)

In [ ]:
a1=np.ones(3,dtype=int)
print(a1)

[1 1 1]


In [ ]:
a1=np.ones([3,4],dtype=int)
print(a1)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [ ]:
type(a1)

numpy.ndarray

In [ ]:
 import numpy as np
 F1=np.full([5,6],72)
 print(F1)

[[72 72 72 72 72 72]
 [72 72 72 72 72 72]
 [72 72 72 72 72 72]
 [72 72 72 72 72 72]
 [72 72 72 72 72 72]]


In [ ]:
F1=np.full([5,6,7],99)
print(F1)

[[[99 99 99 99 99 99 99]
  [99 99 99 99 99 99 99]
  [99 99 99 99 99 99 99]
  [99 99 99 99 99 99 99]
  [99 99 99 99 99 99 99]
  [99 99 99 99 99 99 99]]

 [[99 99 99 99 99 99 99]
  [99 99 99 99 99 99 99]
  [99 99 99 99 99 99 99]
  [99 99 99 99 99 99 99]
  [99 99 99 99 99 99 99]
  [99 99 99 99 99 99 99]]

 [[99 99 99 99 99 99 99]
  [99 99 99 99 99 99 99]
  [99 99 99 99 99 99 99]
  [99 99 99 99 99 99 99]
  [99 99 99 99 99 99 99]
  [99 99 99 99 99 99 99]]

 [[99 99 99 99 99 99 99]
  [99 99 99 99 99 99 99]
  [99 99 99 99 99 99 99]
  [99 99 99 99 99 99 99]
  [99 99 99 99 99 99 99]
  [99 99 99 99 99 99 99]]

 [[99 99 99 99 99 99 99]
  [99 99 99 99 99 99 99]
  [99 99 99 99 99 99 99]
  [99 99 99 99 99 99 99]
  [99 99 99 99 99 99 99]
  [99 99 99 99 99 99 99]]]


In [ ]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
add=np.add(a,b)
print(add)
sub=np.subtract(a,b)
print(sub)
mul=np.multiply(a,b)
print(mul)
div=np.divide(a,b)
print(div)


[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
